#ifndef __display_core_h__
#define __display_core_h__

#include <SDL/SDL_video.h>
#include "core.types.h"

enum display_attrib_e {

  DISPLAY_RED_BITS = SDL_GL_RED_SIZE,
  DISPLAY_GREEN_BITS = SDL_GL_GREEN_SIZE,
  DISPLAY_BLUE_BITS = SDL_GL_BLUE_SIZE,
  DISPLAY_ALPHA_BITS = SDL_GL_ALPHA_SIZE,

  DISPLAY_DEPTH_BITS = SDL_GL_DEPTH_SIZE,
  DISPLAY_BUFFER_BITS = SDL_GL_BUFFER_SIZE,
  DISPLAY_STENCIL_BITS = SDL_GL_STENCIL_SIZE,

  DISPLAY_ACCUM_RED_BITS = SDL_GL_ACCUM_RED_SIZE,
  DISPLAY_ACCUM_GREEN_BITS = SDL_GL_ACCUM_GREEN_SIZE,
  DISPLAY_ACCUM_BLUE_BITS = SDL_GL_ACCUM_BLUE_SIZE,
  DISPLAY_ACCUM_ALPHA_BITS = SDL_GL_ACCUM_ALPHA_SIZE,
  
  DISPLAY_DOUBLEBUFFER = SDL_GL_DOUBLEBUFFER,
  DISPLAY_STEREO = SDL_GL_STEREO,
  DISPLAY_MULTISAMPLE_BUFFERS = SDL_GL_MULTISAMPLEBUFFERS,
  DISPLAY_MULTISAMPLE_SAMPLES = SDL_GL_MULTISAMPLESAMPLES,

  DISPLAY_VSYNC = SDL_GL_SWAP_CONTROL,

  DISPLAY_REQUIRE_ACCEL = SDL_GL_ACCELERATED_VISUAL

};  

enum display_flags_e {

  DISPLAY_FULLSCREEN = SDL_FULLSCREEN,
  DISPLAY_RESIZABLE = SDL_RESIZABLE,
  DISPLAY_NOFRAME = SDL_NOFRAME

};

int set_DISPLAY( int width, int height, int bpp, int flags, ... );
int check_DISPLAY( int width, int height, int bpp, int flags );

#endif
